#
#  _ _____ _     _            _
# (_)___ /| |__ | | ___   ___| | _____
# | | |_ \| '_ \| |/ _ \ / __| |/ / __|
# | |___) | |_) | | (_) | (__|   <\__ \
# |_|____/|_.__/|_|\___/ \___|_|\_\___/

align=center
separator_block_width=15
markup=pango

[idioma]
command=~/Scripts/i3modules/idioma.sh
interval=once
signal=2

[wifi]
command=~/Scripts/i3modules/wifi.sh
interval=10

[volumen]
command=~/Scripts/i3modules/volumen.sh
interval=once
signal=1

[battery]
command=~/Scripts/i3modules/battery.sh
interval=5

[time]
command=date '+%d %b %H:%M'
interval=1

[menu]
full_text= 
command=~/Scripts/i3modules/menu.sh
