# i3status configuration file de plato!! :3
# ß
# see "man i3status" for documentation.

general {
        colors = true
        interval = 1
	markup = pango
}

order += "wireless _first_"
order += "battery all"
order += "volume master"
order += "tztime local"

wireless _first_ {
        format_up = "<span color='#FFFFFF'>%essid</span>"
        format_down = "down"
}

volume master {
        format = "󰓃 %volume"
        format_muted = "󰓃 muted"
        device = "pulse"
        mixer = "Master"
        mixer_idx = 0
}

battery all {
        format = "%status %percentage"
	integer_battery_capacity = true
	last_full_capacity = true
	status_chr = "󱐋"
	status_bat = "󰁹"
}

tztime local {
        format = "%d %b %H:%M"
}
