;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   Hecho para la compu de plato !! :3
;
;==========================================================

[colors]
background = #1C1E26
foreground = #D3DAE3
primary = #E95678
alert = #B81D13
disabled = #53565F

[bar/example]
fixed-center = true
width = 100%
height = 20pt
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 1pt
padding-left = 0
padding-right = 1
module-margin = 1
font-0 = FiraMono Nerd Font:size=14;2

modules-left = workspaces
modules-center = date
modules-right = keyboard wifi volume battery menu

cursor-click = pointer
cursor-scroll = ns-resize

[module/workspaces]
type = internal/i3

label-focused = %name%
label-focused-foreground = #FFFFFF
label-focused-underline = ${colors.primary}
label-focused-padding = 5pt

label-unfocused = %name%
label-unfocused-foreground = ${colors.disabled}
label-unfocused-padding = 5pt

label-urgent = %name%
label-urgent-underline = ${colors.disabled}
label-urgent-background = ${colors.alert}
label-urgent-padding = 5pt

[module/date]
type = internal/date
interval = 1

date = %d %b %H:%M
label = %date%
label-foreground = ${colors.foreground}

[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = caps lock
label-layout = %layout%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{A1:alacritty -e nmtui &:}%{F#B81D13}󰖪 down%{F-}%{A}

[module/wifi]
inherit = network-base
interface-type = wireless
label-connected = %{A1:alacritty -e nmtui &:}󰖩 %essid%%{A}

[module/volume]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
click-right = pavucontrol
label-muted = 󰝟 mute
label-muted-foreground = ${colors.disabled}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
interval = 5

format-charging = <label-charging>
label-charging = %{F#FFEF00}󱐋%{F-} %percentage%%

format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
ramp-capacity-0 = %{F#B81D13}󰂎%{F-}
ramp-capacity-1 = 󰁻
ramp-capacity-2 = 󰁾
ramp-capacity-3 = 󰂀
ramp-capacity-4 = 󰁹

format-full = <label-full>
label-full = %{F#228B22}󰁹%{F-} FULL

[module/menu]
type = custom/text
content = 󰐥
click-left = bash /home/alejandro/i3wm/scripts/menu

[settings]
screenchange-reload = true
pseudo-transparency = true
