# i3blocks config file
#
# i3blocks config para la compu de plato !! :3
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# Global properties
command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=pango

[lang]
command=bash /home/alejandro/i3wm/scripts/lang
interval=once
signal=11

[wifi]
command=bash /home/alejandro/i3wm/scripts/wifi
interval=30

[volume]
command=bash /home/alejandro/i3wm/scripts/volume
interval=once
signal=10

[battery]
command=bash /home/alejandro/i3wm/scripts/battery
interval=30

[time]
command=date '+%H:%M '
interval=5
