#!/usr/bin/bash

# Funcion para encontrar el monitor conectado
monitor() {
if xrandr | grep "DP-1 disconnected"; then
	monitor="DP-2"
elif xrandr | grep "DP-2 disconnected"; then
	monitor="DP-1"
else
	monitor="HDMI-1" 
fi
}

monitor
externo=$monitor

# Apagar interno y prender externo
xrandr --output eDP-1 --off
xrandr --output "$externo" --mode 1920x1080 --rate 60.00 --primary 
