#!/usr/bin/bash

monitor() {
if xrandr | grep "DP-1 disconnected"; then
	monitor="DP-2"
elif xrandr | grep "DP-2 disconnected"; then
	monitor="DP-1"
else
	monitor="HDMI-1" 
fi
}

monitor
externo=$monitor

xrandr --output eDP-1 --off
xrandr --output "$externo" --mode 1920x1080 --rate 60.00 --primary 
