#!/bin/bash

display="󰍹 display"
power="󰐥 power"
audio="󰓃 audio"

mirror="󰍺 mirror"
external="󰍹 external"
laptop="󰌢 laptop"

shutdown="󰐥 shutdown"
reboot="󰜉 reboot"
suspend="󰒲 suspend"
logout="󰌾 log out"

headset="󰋎 headset"
speakers="󰌢 laptop"

display() {
monitor=$(xrandr | grep " connected " | awk 'NR==2 {print$1}')
pantalla=$(echo -e "$mirror\n$external\n$laptop" | rofi -lines 8 -dmenu -p "display")
case $pantalla in
	$mirror)
		xrandr --output eDP-1 --mode 1920x1080 --rate 60.00 --primary --output "$monitor" --same-as eDP-1 ;;
	$external)
		xrandr --output eDP-1 --off --output "$monitor" --mode 1920x1080 --rate 60.00 --primary ;;
	$laptop)
	xrandr --output "$monitor" --off --output eDP-1 --mode 1920x1080 --rate 60.00 --primary ;;
esac
}

power() {
menu=$(echo -e "$shutdown\n$reboot\n$suspend\n$logout" | rofi -lines 8 -dmenu -p "power")
case $menu in
	$shutdown)
		systemctl poweroff ;;
	$reboot)
		systemctl reboot ;;
	$suspend)
		systemctl suspend ;;
	$logout)
		i3-msg exit ;;
esac
}

audio() {
parlante=$(echo -e "$headset\n$speakers" | rofi -lines 8 -dmenu -p "audio")
case $parlante in
	$headset)
		pactl set-default-sink alsa_output.usb-Logitech_G733_Gaming_Headset-00.analog-stereo ;;
	$speakers)
		pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink ;;
esac
}

chosen=$(echo -e "$display\n$power\n$audio" | rofi -lines 8 -dmenu -p "menu")
case $chosen in
	$display)
		display ;;
	$power)
		power ;;
	$audio)
		audio ;;
esac
