#!/usr/bin/bash

opciones="display\npower"
menu=$(echo -e "$opciones" | dmenu -i -p "menu:")

if [[ "$menu" == "display" ]]; then
	display=$(echo -e "mirror\nexterno\nlaptop" | dmenu -i -p "menu:")
	case "$display" in
		mirror) bash ~/i3wm/scripts/mirror ;;
		externo) bash ~/i3wm/scripts/externo ;;
		laptop) bash ~/i3wm/scripts/laptop ;;
	esac
elif [[ "$menu" == "power" ]]; then
	power=$(echo -e "shutdown\nreboot\nsuspend" | dmenu -i -p "menu:")
	case "$power" in
		shutdown) systemctl poweroff ;;
		reboot) systemctl reboot ;;
		suspend) systemctl suspend ;;
	esac
fi
