#!/usr/bin/bash

opciones=("audífonos\nparlante")
menu=$(echo -e "$opciones" | dmenu -i -p "menu:")

if [[ "$menu" == "audífonos" ]]; then
	pactl set-default-sink alsa_output.usb-Logitech_G733_Gaming_Headset-00.analog-stereo
	pactl set-default-source alsa_input.usb-Logitech_G733_Gaming_Headset-00.mono-fallback
elif [[ "$menu" == "parlante" ]]; then
	pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink
	pactl set-default-source alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__source
fi
