#!/usr/bin/bash

amarillo="#EFB700"
blanco="#D3DAE3"

volumen=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -n 1)
mute=$(pactl get-sink-mute @DEFAULT_SINK@)

if [[ "10" -ge "$volumen" ]]; then
	symbol="󰕿"
elif [[ "25" -ge "$volumen" ]]; then
	symbol="󰖀"
else
	symbol="󰕾"
fi


if [[ "$mute" == "Mute: yes" ]]; then
	echo "<span color='$amarillo'>󰝟</span> <span color='$amarillo'>mute</span>"
else
	echo "<span color='$blanco'>$symbol</span> <span color='$blanco'>$volumen%</span>"
fi
